language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - secure: "IY5z55E1ShH8NkTj16XZvL9GE+j5n8fxdo9S8lDoky3Z94zRqLcka60twbhPHKL6zXWS2OHhEjNOadmVujFprib8DsGh00EOV75lGRsW7SZCTHBmEj0JxasOajj5VGxAemqjJMpE3btqJUXp6PsBVRBaM32alswaoMVuvflQKZv9jrb+VsRoVaT9wAPD9wqQXb27/P2H5ad+7DxT6lua7PIgAtNl5p8wKv5+u+Q5acfPuvS5d5GOjA8S4IgKj5lidg1hOvpwWN0pEDJZnQILRVra9/0n+fAn0Y0aNfRMDETSoxKpXFCFL2xbDtGLedu7G146JsTVt1uCV37tO8vuosKc57FGF1tVVNmV5jMg5ackuaImQ+5SdftEznsbhXjRRWeTLvgtvCX33CRI7vddeXHm8UmOcpCfuHiDCt8jAS82yk6ivgoJd1SSnS1eSOzjh0JZ25ZGOwg3NGBewf3mtR/EnXb9LzmZLb13HGRVM3fTYTRQbJ7EovXLBMRfPXn45L7O8tVBPK1vFAe+Y+fw0ToXX2zpMUqUAcshxGoDJZdrU1veLnUOHvO2Q++6wmMWOATl085lGQm87o9XJzDjctgwP+2jQrvD7bvuHM75lrpekbF65tvM+OZhQIrFA0Gp4qfSarkH1B+8jwZzKrZ3D1HKO8+Hv9HQbYggOZQJ2nQ="
    - GH_REPO: github.com/locomotivemtl/charcoal-view.git

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly

before_script:
  ## Init composer
  - composer selfupdate --quiet
  - composer install -n --dev

  ## Create temporary folders
  - mkdir -p build/logs

script:
  ## Lint PHP Files
  - find {src,tests} -name '*.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1

  ## PHP Code Sniffer
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpcs -ps --colors --standard=phpcs.xml src/; fi

  ## Run PHPUnit Tests
  - phpunit --configuration ./tests/phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - bash build/travis/phpdoc_ghpages.sh
  - bash build/travis/apigen_ghpages.sh

notifications:
  slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
  email: charcoal@locomotive.ca
