language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then pear install pear/PHP_CodeSniffer && phpenv rehash; fi"
  - mkdir -p ./tests/tmp/images

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: 
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpcs -ps --colors --standard=phpcs.xml src/; fi"
  - phpunit --bootstrap ./tests/bootstrap.php --configuration ./tests/phpunit.xml --coverage-text

