language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    global:
        - secure: "m+jzzHMxufzVgvs7DUIOYTU6XMVoOVdbrOX7RVvD9DHWqmtMwinhmFwodTT+wKbTTAdXl+Czc35toWQyEYV7DVRP04RccQ3ImeNYATecKo6WokmhPX961OoQgVwDgldNEwxXBCf2TsSgplnG2N8XOXFVjM+H/FP8W2FMBoLbqmnGWjLRwJkHooEhXyYrOIk0ub5Oow9wULKVfWY0RvA9rIZq5UstAD9x/PyIXC0zhi+c7S1/vFELactMkRHX7x2+bJNJxGOVmbxIdQMd9j+Sm3xIs3qqYFF69TYy/3EOZbZwZ33XTOukNFY0+9ZBmnsAc/tVAiti3CUJuldztHHIK0adXle8Ee5SDLmUpdPkb+kZLsSFIry08EGzZ5xqm0FploT/wMZI0/QxaUcaI8dbPyBVPHisEkh9RFsfSapxl0cNCR/+HFO9+Lde6TV6XrcdtMgjEYVSQsA/TSZ3b8DEJQYJORIn/bUOddH2xoy7IyLoqUVn+EMowil8wutn6okikmubA4vTnWi031sfwUKNiPrRzJqXaDlAIJ0wEKHDw3QyHjbt5ykAZ4LYK9pMvOMSTePvH7JWkQZC50G0NS2oaH7d/7svAltgSHJ2IvALs2YRhIvHzY7t6isX2UzNhzc7eHglF/TuipBVdm6nVj8+7FPThjByorcBWE3Fmr7svCI="
        - GH_REPO: github.com/locomotivemtl/charcoal-config.git

matrix:
    allow_failures:
        - php: nightly

before_install:
    - composer self-update --quiet

install:
    - composer install --no-interaction --no-suggest
    - mkdir -p build/logs/

script:
    - composer phplint
    - composer phpcs
    - composer phpunit

after_success:
    - php vendor/bin/php-coveralls -v
    - bash build/travis/phpdoc_ghpages.sh
    - bash build/travis/apigen_ghpages.sh

notifications:
    slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
    email: charcoal@locomotive.ca
