language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    global:
        - secure: "junCzJgs0wOv6JQQJ1Aax3/OS/LF0tiKESK98kQv1OBF3/QaWw8lPecZCK2FTQphfL1/nBXPXR//2MDZ6jny48mUZzDO1my0f+lU3gW2fUTlPD/ALV0UQSh5kHB9yDRpaGRX2z3+QARrwS0voIA2AkVv9qZWE7fl07XSCfHAyA4B5B7Ym6fWMqzUC9xynBJeqK8XUPB62ugqhRJauFNZrGauon17sVm205vnqEhEWl6q8afRz+wtUtQpK8YBCTciCq4dEukb/cnkP8E5a1slOx1AwndA14kWTlHPF3f3OEXHBnzjE62NDd118xzmGN1/9ejlQjnGVr1YB0+EPx1KncPUM0o8Jp+V3wv0ynpmSP92jSuC3XCB0QDScBGAN7pfIoUldsmHwe3mGXzBq7WnoaPyOKELAkfCSYitR2XIX8s+NgzCsqUDvuCyyHN7Rf7JJSvfnZPmJENGZrm3VqJ5s0VXHPIEK3vXXi0rfyddXEnBeIy/vqq8ckgp4jWN7f6DllIEfjRI4C3ougdfaobyNB37OmIVhsc3r+oS20C9Vgq8KFx6cyMa76BjGSBNr4Ir/EGPWLZ1wNEoevLE88ALVEyvx75vX/2yrwt0jYz+gQ3cfZudtodq8UIwff6vfRRKll++cfxBsqWJwlhWaGgdhxaKbA15xGLGRDbmRM96zQA="
        - GH_REPO: github.com/locomotivemtl/charcoal-core.git

matrix:
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update --quiet

install:
    - composer install --no-interaction --no-suggest
    - mkdir -p build/logs/

script:
    - composer phplint
    - composer phpcs
    - composer phpunit -- --coverage-clover "build/logs/clover.xml"

after_success:
    - php vendor/bin/php-coveralls -v
    - bash build/travis/phpdoc_ghpages.sh
    - bash build/travis/apigen_ghpages.sh

notifications:
    slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
    email: charcoal@locomotive.ca
