name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      base:
        description: The base branch to pull into
        required: true
        default: 'main'
      user_name:
        description: The user name requesting the pull.
        required: false
        default: ''

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: bahmutov/npm-install@v1

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract changelog
        shell: bash
        run: |
          git switch ${{ github.event.inputs.base }}
          git switch -
          CHANGELOG=$(./build/script/create-release-notes --from ${{ github.event.inputs.base }} --group)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT
        id: extract_changelog

      # This action is deprecated and should be replaced
      # with something like GitHub CLI.
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ steps.get_workflow_token.outputs.token }}
          source_branch: ${{ steps.extract_branch.outputs.branch }}
          destination_branch: ${{ github.event.inputs.base }}
          pr_title: "Pulling ${{ steps.extract_branch.outputs.branch }} into ${{ github.event.inputs.base }}"
          pr_body: |
            # Merge ${{ steps.extract_branch.outputs.branch }} into ${{ github.event.inputs.base }}
            ${{ steps.extract_changelog.outputs.changelog }}
          pr_reviewer: "@charcoalphp/reviewers"          # Comma-separated list (no spaces
          pr_label: release,automatic-pr                 # Comma-separated list (no spaces)
          pr_draft: false                                # Creates pull request as draft
          pr_allow_empty: false                          # Creates pull request even if there are no changes

