name: Release

on:
  workflow_run:
    workflows: [ PHP Testing ]
    types: [ completed ]
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: bahmutov/npm-install@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      # semantic release local configuration needs to call ./vendor/bin/monorepo-builder
      - name: Install Dependencies
        uses: ramsey/composer-install@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          semantic_version: 19
