name: Split Monorepo

on:
    push:
        branches:
            - main
        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    provide_packages_json:
        # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
        # see https://stackoverflow.com/a/62953566/1348344
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # required for matrix of packages set
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            # get package json list
            -   id: output_data
                run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

        # this step is needed, so the output gets to the next defined job
        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    split_monorepo:
        needs: provide_packages_json

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

            matrix:
                # define package to repository map
                package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

        steps:
            -   uses: actions/checkout@v2

            # no tag
            -   if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.1"
                name: Monorepo Split of ${{ matrix.package }}
                with:
                    # ↓ split "packages/[local_path]" directory
                    package_directory: 'packages/${{ matrix.package }}'

                    # ↓ into locomotive-charcoal/[split_repository] repository
                    repository_organization: 'locomotive-charcoal'
                    repository_name: '${{ matrix.package }}'

                    # [optional, with "github.com" as default]
                    #repository_host: git.private.com:1234

                    # ↓ the user signed under the split commit
                    user_name: "GitHub Action"
                    user_email: "action@github.com"
                    branch: "main"

            # with tag
            -   if: "startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.1"
                name: Monorepo Tagged Split of ${{ matrix.package }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    # ↓ split "packages/[local_path]" directory
                    package_directory: 'packages/${{ matrix.package }}'

                    # ↓ into locomotive-charcoal/[split_repository] repository
                    repository_organization: 'locomotive-charcoal'
                    repository_name: '${{ matrix.package }}'

                    # [optional, with "github.com" as default]
                    #repository_host: git.private.com:1234

                    # ↓ the user signed under the split commit
                    user_name: "GitHub Action"
                    user_email: "action@github.com"
                    branch: "main"
