name: 'Packages Split'

on:
    push:
        branches:
            - main

        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

    pull_request: null

    release:
        types: [ created ]

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

            matrix:
                # define package to repository map
                package:
                    -   local_path: 'charcoal-admin'
                        split_repository: 'charcoal-admin'
                    -   local_path: 'charcoal-app'
                        split_repository: 'charcoal-app'

        steps:
            -   uses: actions/checkout@v2

            # no tag
            -   if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.1"
                with:
                    # ↓ split "packages/[local_path]" directory
                    package_directory: 'packages/${{ matrix.package.local_path }}'

                    # ↓ into locomotive-charcoal/[split_repository] repository
                    repository_organization: 'locomotive-charcoal'
                    repository_name: '${{ matrix.package.split_repository }}'

                    # [optional, with "github.com" as default]
                    #repository_host: git.private.com:1234

                    # ↓ the user signed under the split commit
                    user_name: "kaizen-ci"
                    user_email: "info@kaizen-ci.org"


            # with tag
            -   if: "startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.1"
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    # ↓ split "packages/[local_path]" directory
                    package_directory: 'packages/${{ matrix.package.local_path }}'

                    # ↓ into locomotive-charcoal/[split_repository] repository
                    repository_organization: 'locomotive-charcoal'
                    repository_name: '${{ matrix.package.split_repository }}'

                    # [optional, with "github.com" as default]
                    #repository_host: git.private.com:1234

                    # ↓ the user signed under the split commit
                    user_name: "kaizen-ci"
                    user_email: "info@kaizen-ci.org"
